apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tmodloader
  name: tmodloader
  namespace: tmodloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tmodloader
      app.kubernetes.io/component: tmodloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tmodloader
        app.kubernetes.io/component: tmodloader
    spec:
      containers:
        - image: ghcr.io/bobbyrward/tmodloader-docker:v0.0.1
          name: tmodloader-docker
      imagePullSecrets:
        - name: tmodloader-pull-secret
