apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: tmodloader-pull-secret
  namespace: tmodloader
spec:
  encryptedData:
    .dockerconfigjson: AgB0gpySEXaVe/C37PEWBaZDaG/XO8O603xRzhQdyKqsmZVt7z2wMjyFEpBnFtz6oFAVAGi8MwKAcJK+RQIZY78jOJelNZVT4I2oy6n6QitbCk9rRiBL2e92myabEzKJJVa/l7srKtVknRpp7oYL36B/42rR3UBtfP7arC6qW1ycX/Kqcu98fLCpV5go3yUJWigKj1wiAzN3GuhmzBGa2R4HAjWPuWe4bBmeRhLAAfaPK3Y3qtRuVY4y3SVHQeVDw/+DKcjZP+vdfJdxKZlRmZKnmfR9Uzt/Q2WpjfcMIzw+QFtTDf8ZHR3JE90ehXeOBemyTN0pEhcTqGoWVUAhHZJxY7lxJEtQRUeZ+eJFXy2lFCAskhy5FyGxT8f2P2WV8ntJEaB7Fyai8ySQs4+fjHcKU0iTOd6ddXufwuRehRgbe11WepgCuReXlg2awN+LUKaMEnqQCPL90gcbo38EncTPZzAp5ADtiIJGDzGbWwU/FFsBwrzM+zj5OnI0F4t5l7vKqEVOOHD4PxZzoImpxqq+SqQJ+3SLhDkbBQw0BPq8L1//U5WWuIZEKZNoXpmnO1PJqyI42SwMA7c0RHnFqznarZzDsoznOvQARSMtSc+vZCC9PXzcb8zjiawzOOd/6epy3bQ83/wvCc6/LFEdnVxu5xTeOiUwtt1nXlYNdvB6JFPS/ODlilhvpwAN7/u1K7OZGiHAuqCC/DL+yqMnbZLtNjrnvrDYzIK/Xr15ikjbl0ExaBqId1sC4Tu9i/bdeXBsU/BC8Zz4I901qfhkJPZJTCi8QXpfMMjEW1w58LZ/5MXyP9XRusm0kcp/JpiT97tNXaZdTbpqBsPH9UkpLyUBMpSwgowcCJPEhDfSg/mkKWqBZ+qcRD0lNgo626Mkgy7VgyVVZ6uPUusxYIAmQahHELUsBYbxGRAVoU8xbmJyRnWMdA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: tmodloader-pull-secret
      namespace: tmodloader
    type: kubernetes.io/dockerconfigjson

