apiVersion: v1
kind: Service
metadata:
  name: tmodloader
  namespace: tmodloader
spec:
  ports:
    - port: 7777
      name: terraria
      nodePort: 7777
  selector:
    app.kubernetes.io/instance: tmodloader
    app.kubernetes.io/component: tmodloader
  type: NodePort
