apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    repoURL: https://github.com/bobbyrward/home-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
