resources:
  - namespace.yaml
helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.6.0
    namespace: sealed-secrets
    includeCRDs: true
